[build]
builder = "nixpacks"

[deploy]
startCommand = "cd .next/standalone && node server.js"
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
